sudo: required
services:
  - docker

before_install:
  - docker build -t pmacdougall/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pmacdougall/docker-react npm run test -- --coverage
